# Generated by Django 4.2.13 on 2024-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('cusotmer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=12)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
