# Generated by Django 4.2.13 on 2024-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
