# Generated by Django 4.2.13 on 2024-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('cusotmer_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
