# Generated by Django 4.2.13 on 2024-06-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bookingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='cusotmer_email',
            new_name='customer_email',
        ),
    ]
