# Generated by Django 4.2.13 on 2024-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_cusotmer_email_bookingrequest_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='event_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='event_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
