# Generated by Django 4.2.13 on 2024-06-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_bookingrequest_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='read',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
