# Generated by Django 4.2.13 on 2024-06-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_eventmenus'),
        ('events', '0007_rename_read_bookingrequest_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.eventmenus'),
            preserve_default=False,
        ),
    ]
