# Generated by Django 4.2.13 on 2024-06-20 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_alter_review_options_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(related_name='review_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
