# Generated by Django 4.2.13 on 2024-06-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='updated_on',
        ),
    ]
